# 基本配置
BaseConfig: &base
  DEBUG: true
  LOG_LEVEL: "DEBUG"
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SQLALCHEMY_DATABASE_URI: ""
  SECRET_KEY: "#$%^&**$##*(*^%%$**((&"
  JWT_SECRET_KEY: "#$%^&**$##*(*^%%$**((&"
  JWT_ACCESS_TOKEN_EXPIRES: 300
  AccessKeyID: ""
  AccessKeySecret: ""
  Endpoint: ""
  BucketName: ""
  UrlExpires: 60


# 开发配置
DevelopmentConfig:
  <<: *base

# 生产配置
ProductionConfig:
  <<: *base

# 测试配置
TestingConfig:
  <<: *base

# 当前使用配置
CurrentConfig: "DevelopmentConfig"
